Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = false
  end

  # General Libvirt Connection
  config.vm.provider :libvirt do |libvirt|
    libvirt.host = "localhost"
    libvirt.uri = 'qemu+unix:///system'
    libvirt.driver = 'kvm'
    libvirt.memory = '512'
    libvirt.cpus = '1'
  end

  config.vm.define "selinux" do |selinux|
    selinux.vm.box = "centos/7"
    selinux.vm.network "private_network", type: "dhcp"
    selinux.vm.hostname = "selinux.example.com"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end

end